### ISSUE TITLE
With the upgrade test doesn't run

### ISSUE THREAD

**Issue by menka-samtek** [darkmavis1980/react-jest-boilerplate#28]
ReferenceError: TextEncoder is not defined

**Comment by darkmavis1980** [comment]
Thanks for reporting, I'll try to replicate the issue on my side

**Comment by darkmavis1980** [comment]
From my side it seems to work fine, can I ask you which version of Node are you using?

**Comment by darkmavis1980** [comment]
Did a major release, now it supports React 18 and Jest 28, but enzyme has been dropped in favour of react-test-renderer
